### ISSUE TITLE
Complete Reservation Scrapper

### ISSUE THREAD

**Issue by monkin77** [LEIC-ES-2021-22/3LEIC03T1#58]
After talking with the library's staff, we learned that the reservations behavior from start to finish is different from what we we're expecting. As such, we need to update the scrapper logic to fetch reservation and their status correctly

**Comment by ruialves35** [comment]
![image](https://user-images.githubusercontent.com/71840917/170302720-657c6e08-3ffe-47ef-9c90-19a39a9214af.png)

Just letting this here for you to know the message that we get after Reservation being ready to pick up.
When it's not ready, it appears "Em processamento"
